use serde::Serialize;
use serde_json::Value;
use std::process::Command;

/// Rules generated by the firewall carry the comment "iqsoft-rule-<id>".
const RULE_TAG: &str = "iqsoft-rule-";

/// Packet and byte totals for one firewall rule.
/// Totals count since the rules were last committed, because every
/// commit reloads the ruleset and starts the counters again from zero.
#[derive(Debug, Serialize, Clone, PartialEq)]
pub struct RuleCounter {
    pub rule_id: i64,
    pub chain: String,
    pub packets: u64,
    pub bytes: u64,
}

/// Read the counters of every tagged rule in the live ruleset.
pub fn read_rule_counters() -> Result<Vec<RuleCounter>, String> {
    let text = run_nft()?;
    parse_nft_json(&text)
}

fn run_nft() -> Result<String, String> {
    let mut last_error = String::from("nft not found");

    for program in ["/usr/sbin/nft", "/sbin/nft", "nft"] {
        match Command::new(program)
            .args(["-j", "list", "table", "inet", "filter"])
            .output()
        {
            Ok(output) if output.status.success() => {
                return Ok(String::from_utf8_lossy(&output.stdout).into_owned());
            }
            Ok(output) => {
                last_error = format!(
                    "{} failed: {}",
                    program,
                    String::from_utf8_lossy(&output.stderr).trim()
                );
            }
            Err(e) => {
                last_error = format!("{}: {}", program, e);
            }
        }
    }

    Err(format!(
        "Could not read the firewall ruleset ({}). Make sure a ruleset has been committed and the API runs as root.",
        last_error
    ))
}

/// Parses the output of `nft -j list table inet filter`.
///
/// A tagged rule looks like this (shortened):
///   {"rule": {"chain": "input", "comment": "iqsoft-rule-11",
///             "expr": [ ..., {"counter": {"packets": 7, "bytes": 420}}, {"accept": null}]}}
fn parse_nft_json(text: &str) -> Result<Vec<RuleCounter>, String> {
    let root: Value = serde_json::from_str(text)
        .map_err(|e| format!("Could not parse nft output: {}", e))?;

    let items = root
        .get("nftables")
        .and_then(Value::as_array)
        .ok_or_else(|| "Unexpected nft output: no 'nftables' list".to_string())?;

    let mut result = Vec::new();

    for item in items {
        let Some(rule) = item.get("rule") else {
            continue;
        };

        let Some(comment) = rule.get("comment").and_then(Value::as_str) else {
            continue;
        };

        let Some(id_text) = comment.strip_prefix(RULE_TAG) else {
            continue;
        };

        let Ok(rule_id) = id_text.parse::<i64>() else {
            continue;
        };

        let chain = rule
            .get("chain")
            .and_then(Value::as_str)
            .unwrap_or("")
            .to_string();

        let Some(exprs) = rule.get("expr").and_then(Value::as_array) else {
            continue;
        };

        let Some(counter) = exprs.iter().find_map(|e| e.get("counter")) else {
            continue;
        };

        result.push(RuleCounter {
            rule_id,
            chain,
            packets: counter.get("packets").and_then(Value::as_u64).unwrap_or(0),
            bytes: counter.get("bytes").and_then(Value::as_u64).unwrap_or(0),
        });
    }

    result.sort_by(|a, b| {
        a.rule_id
            .cmp(&b.rule_id)
            .then_with(|| a.chain.cmp(&b.chain))
    });

    Ok(result)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_tagged_rule_counters() {
        let sample = r#"{"nftables":[
            {"metainfo":{"version":"1.0.9"}},
            {"table":{"family":"inet","name":"filter","handle":1}},
            {"rule":{"family":"inet","table":"filter","chain":"input","handle":5,
                     "comment":"iqsoft-rule-11",
                     "expr":[
                        {"match":{"op":"==","left":{"payload":{"protocol":"tcp","field":"dport"}},"right":22}},
                        {"counter":{"packets":7,"bytes":420}},
                        {"accept":null}]}},
            {"rule":{"family":"inet","table":"filter","chain":"input","handle":6,
                     "expr":[{"accept":null}]}}
        ]}"#;

        let counters = parse_nft_json(sample).expect("should parse");

        // The second rule has no iqsoft tag, so it is left out.
        assert_eq!(counters.len(), 1);
        assert_eq!(counters[0].rule_id, 11);
        assert_eq!(counters[0].chain, "input");
        assert_eq!(counters[0].packets, 7);
        assert_eq!(counters[0].bytes, 420);
    }

    #[test]
    fn rejects_garbage_output() {
        assert!(parse_nft_json("not json").is_err());
        assert!(parse_nft_json("{}").is_err());
    }
}
